<script type="text/javascript">
    function check(){
        var field = document.getElementById("customapp_messages_sherbo_time").value;
        var form = document.getElementById("config_edit_form");

        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method: 'POST',
            dataType: 'json',
            data: JSON.stringify(form),
            onSuccess: function(transport){
                var response = JSON.parse(transport.responseText);
                if (response.error == 1) {
                    alert('error');
                    console.log(response);
                    return false;
                } else {
                    alert('looza');
                    console.log(response);
                }
            },
            onFailure: function() {
                alert('Something went wrong...');
                console.log('Something went wrong...');
                return false;
            }
        });
    }
</script>

<?php echo $this->getButtonHtml() ?>