<script type="text/javascript">
    function check(){

        var time = $("customapp_messages_sherbo_time").getValue();
        var discount = $("customapp_messages_sherbo_message").getValue();
        var disable = $("customapp_messages_sherbo_select").getValue();
        //alert(disable);
        //alert('<?php echo $this->getAjaxCheckUrl() ?>');
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method: 'POST',
            parameters: {time : time, discount: discount, disable: disable},
            onSuccess: function(transport){
                var response = JSON.parse(transport.responseText);
                if (response.error == 1) {
                    alert('error');
                    console.log(response);
                    return false;
                } else {
                    alert('Request Sent');
                    console.log(response);
                }
            },
            onFailure: function() {
                alert('Something went wrong...');
                console.log('Something went wrong...');
                return false;
            }
        });
    }
</script>

<?php echo $this->getButtonHtml() ?>